### ISSUE TITLE
Some emails are reuploaded without changes, with all attachments uploaded back

### ISSUE THREAD

**Issue by MaxD2** [wolfgangasdf/gmail-attachment-remover#3]
Greetings!
First of all, thank you for the great tool!

After processing most of the big mails, I found out that some mails are reuploaded with all attachments back. That mails are found as big ones on next round again.

Here is the screenshot of situation isolated:

<img width="993" alt="image" src="https://github.com/wolfgangasdf/gmail-attachment-remover/assets/7348925/e8bce78c-7ccd-49af-8ed7-a21c8ebab1b0">

Is it possible to fix this or at least add an option or switch that will disable reuploading attachments all together?

**Comment by MaxD2** [comment]
It seems that the tool doesn't delete inline images - even if they are big (

**Comment by wolfgangasdf** [comment]
Hi, this program is far from perfect, since there are many ways large attachments can be embedded. Currently it doesn't remove inline attachments, it is on my todo list since long (but I don't know if I manage to implement this soon, one has to test this extensively). About the first issue, this should not occur - is it probably an inline image (but I think not)? Have you selected "backup messages" (which makes it unusably slow in the first place)? If you want and the email is not confidential, you could forward to me and I test it: wolfgang.loeffler@gmail.com.

**Comment by MaxD2** [comment]
Yep, that is inline images too.

What if just simply skip adding inline image part if it is larger then minimum attachment size?
